kiboko_dam_bundle:
    resource: "@KibokoDAMBundle/Controller"
    type:     annotation
    prefix:   %web_backend_prefix%/dam

kiboko_dam.api.document:
    resource: '@KibokoDAMBundle/Controller/Api/Rest/DocumentController.php'
    type: rest
    prefix: api/rest/{version}/
    requirements:
        version: latest|v1
        _format:  json
    defaults:
        version: latest
