services:
    kiboko_dms.integration.channel:
        class: Kiboko\Bundle\DMSBundle\Integration\Channel
        tags:
            - { name: oro_integration.channel, type: kiboko_dms }

    kiboko_dms.integration.form.local:
        class: Kiboko\Bundle\DMSBundle\Form\Type\LocalAdapterType
        arguments:
            - "@oro_integration.manager.types_registry"
        tags:
            - { name: form.type }

    kiboko_dms.integration.transport.local:
        class: Kiboko\Bundle\DMSBundle\Integration\LocalTransport
        tags:
            - { name: oro_integration.transport, channel_type: kiboko_dms, type: local }

    kiboko_dms.integration.form.flyimg:
        class: Kiboko\Bundle\DMSBundle\Form\Type\FlyimgAdapterType
        arguments:
            - "@oro_integration.manager.types_registry"
        tags:
            - { name: form.type }

    kiboko_dms.integration.transport.flyimg:
        class: Kiboko\Bundle\DMSBundle\Integration\FlyimgTransport
        tags:
            - { name: oro_integration.transport, channel_type: kiboko_dms, type: flyimg }
