services:
    kiboko_dam.form.type.document:
        class: Kiboko\Bundle\DAMBundle\Form\Type\DocumentType
        arguments:
            - '@oro_security.token_accessor'
        tags:
            - { name: form.type }

    kiboko_dam.form.document:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'kiboko_dam_document_form'
            - Kiboko\Bundle\DAMBundle\Form\Type\DocumentType

    kiboko_dam.form.handler.document:
        class: Kiboko\Bundle\DAMBundle\Form\Handler\DocumentHandler
        arguments:
            - '@kiboko_dam.form.document'
            - '@request_stack'
            - '@doctrine.orm.entity_manager'

    kiboko_dam.controller.document:
        class: Kiboko\Bundle\DAMBundle\Controller\DocumentController
        arguments:
            - '@kiboko_dam.form.document'
            - '@kiboko_dam.form.handler.document'
            - '@translator'
            - '@oro_ui.router'
            - '@session'

    kiboko_dam.form.type.document_node:
        class: Kiboko\Bundle\DAMBundle\Form\Type\DocumentNodeType
        arguments:
            - '@oro_security.token_accessor'
        tags:
            - { name: form.type }

    kiboko_dam.form.document_node:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'kiboko_dam_document_form'
            - Kiboko\Bundle\DAMBundle\Form\Type\DocumentNodeType

    kiboko_dam.tree.document_node_update_tree_handler:
        class: Kiboko\Bundle\DAMBundle\JsTree\DocumentNodeUpdateTreeHandler
        arguments:
            - '@translator'
            - '@oro_locale.helper.localization'
            - '@doctrine.orm.entity_manager'


    kiboko_dam.controller.document_node:
        class: Kiboko\Bundle\DAMBundle\Controller\DocumentNodeController
        arguments:
            - '@kiboko_dam.form.document_node'
            - '@oro_form.update_handler'
            - '@translator'
            - '@kiboko_dam.tree.document_node_update_tree_handler'

    kiboko_dam.form.type.team_storage:
        class: Kiboko\Bundle\DAMBundle\Form\Type\TeamStorageNodeType
        arguments:
            - '@oro_security.token_accessor'
        tags:
            - { name: form.type }

    kiboko_dam.form.team_storage:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'kiboko_dam_document_form'
            - Kiboko\Bundle\DAMBundle\Form\Type\TeamStorageNodeType

    kiboko_dam.controller.team_storage:
        class: Kiboko\Bundle\DAMBundle\Controller\TeamStorageNodeController
        arguments:
            - '@kiboko_dam.form.team_storage'
            - '@oro_form.update_handler'
            - '@translator'

    kiboko_dam.listener.navigation_listener:
        class: Kiboko\Bundle\DAMBundle\EventListener\NavigationListener
        arguments:
            - '@oro_locale.helper.localization'
            - '@oro_entity.doctrine_helper'
            - '@oro_entity_config.provider.entity'
            - '@oro_security.token_accessor'
            - '@oro_security.acl_helper'
            - '@oro_featuretoggle.checker.feature_checker'
        tags:
            - { name: kernel.event_listener, event: oro_menu.configure.application_menu, method: onNavigationConfigure }

    kiboko_dam.event_listener.document_datagrid:
        class: Kiboko\Bundle\DAMBundle\EventListener\DocumentDatagridListener
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.kiboko-dam-documents-grid, method: onBuildBefore }

    kiboko_dam.document_manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - Kiboko\Bundle\DAMBundle\Entity\Document
            - '@doctrine.orm.entity_manager'

